### ISSUE TITLE
Research and choose GUI Dependencies

### ISSUE THREAD

**Issue by JordanPaoletti** [JordanPaoletti/Conflict_Checker#3]
We will likely use the tornado FX kotlin wrapperfor javaFX. However, we may want to find solutions for dragging and dropping files and similar functionality.

**Comment by kolthahn97** [comment]
Just as you stated, using tornado FX to accomplish this is possible.  I found a similar question here:
https://stackoverflow.com/questions/32534113/javafx-drag-and-drop-a-file-into-a-program
that offers solutions for onDrag() onDrop() etc.  TornadoFX does not directly implement this functionality but because it is a wrapper for JavaFX
